### ISSUE TITLE
Module parse failed: Unexpected token (27713:39)

### ISSUE THREAD

**Issue by reibanaag** [stellR42/vue3-pdf-app#1]
I tried using your package however I am getting this error when compiling:

![image](https://user-images.githubusercontent.com/77881215/204039749-73aa916a-0f78-418c-8cb1-0a960a9755ae.png)

I hope you can check the error.

Thank you

**Comment by stellR42** [comment]
Please provide a minimal reproducible example or at least your configuration files.
