### ISSUE TITLE
i10n doesnot work well

### ISSUE THREAD

**Issue by maxrks** [stellR42/vue3-pdf-app#10]
This package is excellent!
There might be a bug related to internationalization (i10n) when importing the i10n module.

by the instruction, add the markup into index.html
` <link rel="resource" type="application/l10n" href="./viewer.properties" />`
then reload the current workspace, the pdf viewer would work at first, but  a second time the viewer's content would be blank.
<img width="1327" alt="Snipaste_2023-07-17_12-29-22" src="https://github.com/stellR42/vue3-pdf-app/assets/20557631/dea4d348-fa79-4f35-9a40-7ab44b4dfc19">

It appears that some key-value pairs are missing in the viewer.properties file. I attempted to add them, but they did not have the desired effect or did not work as expected.

**Comment by stellR42** [comment]
The viewer.properties file is not included. 
1. Take a desired locale [from here](https://github.com/mozilla/pdf.js/blob/master/l10n/ko/viewer.properties?rgh-link-date=2021-04-06T20%3A50%3A31Z)
2. Copy paste it into a file in your project (locale.txt for instance)
3. Add `<link rel="resource" type="application/l10n" href="path-to-the-locale.txt" />` into your html
