### ISSUE TITLE
Console errors: offsetParent not set, navigateTo: "null"

### ISSUE THREAD

**Issue by jasonwmatteson** [stellR42/vue3-pdf-app#11]
I have the following code used in a component:

```
<script setup lang="ts">
import { ref } from 'vue';
import VuePdfApp from 'vue3-pdf-app';
import 'vue3-pdf-app/dist/icons/main.css';

const pdf = ref('a valid path to a valid pdf file');
</script>
<template>
  <div>
    <VuePdfApp
      :pdf="pdf"
    />
  </div>
</template>
```
When I load the page I get the following errors:

```
ui_utils.js:145 offsetParent is not set -- cannot scroll
pdf_link_service.js:153 PDFLinkService.navigateTo: "null" is not a valid destination array, for dest="/".
```

I am running this in an Electron app created via the Quasar Framework using Vite and Vue 3 (3.2.30). This cannot rely on the internet to function.

**Comment by jasonwmatteson** [comment]
I also updated to vue 3.2.33 and the errors persist.

**Comment by jasonwmatteson** [comment]
I figured it out although I still get some errors. I will open a new issue if I continue to get them.

**Comment by Tonight11** [comment]
Have u solved it? and how?
