### ISSUE TITLE
How do I set up cMapUrl

### ISSUE THREAD

**Issue by jiazhigang727** [stellR42/vue3-pdf-app#16]
Please provide a working example with a bug (git repo, [codesandbox](https://codesandbox.io/), source code at least, etc).
It takes a lot of time to set up environment to confirm an issue.
So I will resolve issues faster.

#### Configuration:
- Web browser and it`s version:
- Operating system and it`s version:
- vue-pdf-app version:

**Comment by udbnui** [comment]
1、把cmaps目录copy到public/web/目录下及可。
2、cmaps可在\vue3-pdf-app\src\pdfjs-dist找到。
