### ISSUE TITLE
Cors error when pdf load from another server

### ISSUE THREAD

**Issue by safi-okz** [stellR42/vue3-pdf-app#22]
I want to load a pdf file from another server and show but here the CORS error comes and the pdf did not loaded.

**Comment by locionic** [comment]
I am also having the same issue.
Pdf url: https://www.africau.edu/images/default/sample.pdf
![image](https://github.com/stellR42/vue3-pdf-app/assets/47636017/5d6c85ae-599f-4b96-b6a6-6a46eca9beea)

**Comment by stellR42** [comment]
You need to enable CORS on your server. This error cannot be handled by this project. See https://stackoverflow.com/a/25311247

**Comment by neomib-paylists** [comment]
I also had a CORS problem. I'm using firebase storage to store my files.
This answer helped me : https://stackoverflow.com/a/58613527/7649991
