### ISSUE TITLE
Can't use multiple viewer at the same time in same page

### ISSUE THREAD

**Issue by barisener** [stellR42/vue3-pdf-app#25]
Can't use multiple viewer at the same time in same page

#### Configuration:
-

#### Steps to reproduce the problem:
Use multiple pdf viewer in same page, you can reproduce it

#### What is the expected behavior?
It should render multiple pdf.

#### What went wrong?
First pdf is showing but second and third one is not looking.

#### Attachments (screenshots, links, etc)
-

**Comment by Tonight11** [comment]
Have you solved this problem?

**Comment by barisener** [comment]
@Tonight11 no i couldn't. I forked and fix it than i used.
