### ISSUE TITLE
pdf文件内容显示不完整

### ISSUE THREAD

**Issue by xian-621** [stellR42/vue3-pdf-app#27]
pdf文件有一些会显示的不完整，比如发票的pdf文件，只显示了里面的纳税人识别号，但是名称没有信息，url地址在浏览器查看是没问题的

**Comment by xian-621** [comment]
一个发票pdf文件，现在显示的是
![Snipaste_2024-07-02_10-09-10](https://github.com/stellR42/vue3-pdf-app/assets/58378900/4898f94b-0d3e-40d5-b198-5a1503b84d2e)
地址复制出来显示的是完整的

**Comment by horizon188** [comment]
有pdf原件吗
