### ISSUE TITLE
在el-dialog弹窗使用有bug

### ISSUE THREAD

**Issue by raochongmou** [stellR42/vue3-pdf-app#28]
弹窗第一次打开时内容能正常显示，但是报错如图所示：![1722000316540](https://github.com/user-attachments/assets/634d1de0-41e6-4e74-83f2-a3ea8c3d686f)
弹窗再次打开时内容就消失了，同时也报了个错误 `offsetParent is not set -- cannot scroll`
组件是按照csdn大佬写的复制粘贴的，不清楚是哪里问题，希望大佬可以抽空帮忙解决一下 谢谢

**Comment by raochongmou** [comment]
![1722000745373](https://github.com/user-attachments/assets/cd4a5a74-e2f2-4df9-831b-2fea3c4f944d)

**Comment by jackChendada** [comment]
解决了吗楼主

**Comment by raochongmou** [comment]
> 解决了吗楼主
换插件了

**Comment by raochongmou** [comment]
> > 解决了吗楼主
> > 换插件了
![image](https://github.com/user-attachments/assets/ebf3c011-ec24-4bf7-92de-66b07d7357ca)

**Comment by jackChendada** [comment]
vue-pdf-embed 我看这个插件很素啊，功能好像没pdf-app多，那些分页打印你是怎么做的啊

**Comment by raochongmou** [comment]
![1722583664912](https://github.com/user-attachments/assets/e2614db9-c799-4cd5-a381-b163f2bc44fa)
我就做了一些简单的功能  可以分页 可以打印  可以下载 可以放大缩小  其余的功能没做

**Comment by raochongmou** [comment]
![1722583798001](https://github.com/user-attachments/assets/b51da4ff-5f7e-46e7-95e2-4b53db471fb1)
我就做了打印、下载、缩小放大、分页这些功能

**Comment by raochongmou** [comment]
![1722583948566](https://github.com/user-attachments/assets/6b92431d-1dab-456f-926e-026a658d8409)
我就做了下载、打印、放大缩小、分页的功能
