### ISSUE TITLE
How to integrated with nuxt 3 ?

### ISSUE THREAD

**Issue by khoazero123** [stellR42/vue3-pdf-app#5]
I got this error when using with Nuxt3 - SSR mode:
```
document is not defined
```

**Comment by stellR42** [comment]
SSR is not supported. Please use `<client-only>`. https://nuxtjs.ir/api/components-client-only

**Comment by Timothy16** [comment]
Even with adding <client-only>, the error is still there

**Comment by MilenaPetkanova** [comment]
I have the same issue. `<client-only>` did not work.
