### ISSUE TITLE
could not parse arguments for #print_progress_percent

### ISSUE THREAD

**Issue by xeniamura** [stellR42/vue3-pdf-app#7]
Hello! 
I have imported your VuePdfApp in my project, and added localization-file with translations as [in examples](https://github.com/mozilla/pdf.js/tree/master/l10n), but I still have issues on my console after the rendering of preview-component:
 
vue3-pdf-app.umd.js?05a4:12973 could not parse arguments for #print_progress_percent
vue3-pdf-app.umd.js?05a4:13682 argument {{progress}} for #print_progress_percent is undefined.

Also it requires swg-image which is supposed to be in node_modules/vue3-pdf-app/dist/img

#### Configuration:
- Chrome 110.0.5481.177 
- MacOs 12,6
- "vue3-pdf-app": "^1.0.3",

#### Steps to reproduce the problem:
add VuePdfApp on my compo
<VuePdfApp :pdf="file.url" :fileName="file.fileName" :config="config"/>
where "url" - is CreateObjectURL from received Blob

#### What is the expected behavior?
{{progress}} changes and shows correctly 

#### What went wrong?
I have warnings in console

#### Attachments (screenshots, links, etc)
<img width="650" alt="Снимок экрана 2023-03-02 в 16 57 21" src="https://user-images.githubusercontent.com/126789880/222449750-92878c21-2d7a-4831-a384-a9e8f4222aff.png">
<img width="512" alt="Снимок экрана 2023-03-02 в 17 10 00" src="https://user-images.githubusercontent.com/126789880/222453336-26457aeb-3074-446f-a7a6-2c1738676c7b.png">
<img width="542" alt="Снимок экрана 2023-03-02 в 17 15 37" src="https://user-images.githubusercontent.com/126789880/222453360-c25dcc96-c783-4d69-9962-097ff6652e14.png">

Any help would be appreciated, thanks a lot.

**Comment by W113N23** [comment]
I have the same problem please
![image](https://user-images.githubusercontent.com/85914874/222607179-fe7468cc-13f6-4c30-8ddf-9b173a12416b.png)

**Comment by W113N23** [comment]
@xeniamura 
![image](https://user-images.githubusercontent.com/85914874/222627886-70f5f97d-29de-44fc-a8eb-313f1734a4fa.png)
use  nextTickt()  Solved the problem of dialog opening

**Comment by xeniamura** [comment]
@W113N23 Thank you.
Unfortunately, nextTick() doesn't work neither for me. I had no problem with opening dialog but these warnings and errors still appear after the modal-compo with vuepdf is opened.

Also, I have noticed the difference between quotes (' and ") in this line for {{scale}} which works correctly and {{progress}}.
<img width="443" alt="Снимок экрана 2023-03-03 в 16 19 53" src="https://user-images.githubusercontent.com/126789880/222730790-5c49843a-cca3-41f6-b763-d8be554cd901.png">

**Comment by W113N23** [comment]
@xeniamura   Yes, he will still report errors. I may not care much about this, as long as it can ensure normal preview of PDF

**Comment by stellR42** [comment]
@xeniamura Is the only issue the warnings in the console? Is the component working fine otherwise?

**Comment by W113N23** [comment]
@stellR42 Yes, the components can be displayed normally, although warning will be printed on the console，
<img width="1623" alt="11" src="https://user-images.githubusercontent.com/85914874/225488301-28cad6ea-db74-46a1-873f-344ed2d4cb7b.png">

**Comment by rassemdev** [comment]
It is also happening to me.

could not parse arguments for #print_progress_percent
argument {{progress}} for #print_progress_percent is undefined.
Warning: Setting up fake worker
offsetParent is not set -- cannot scroll

**Comment by losblancos113** [comment]
Hello @xeniamura, @stellR42 
Have you fixed this issue? I think this issue somehow make the @open event not be triggered
