### ISSUE TITLE
Eval Security Warning

### ISSUE THREAD

**Issue by rtarling** [stellR42/vue3-pdf-app#8]
Hi

Many thanks for creating this package.  It is a nightmare to find a simple wrapper on the PDFJS for Vue/Ionic/Vite.

Will you be keeping this in synch with PDFJS as it improves?

I have one concern, which is this warning: "Use of eval in "node_modules/vue3-pdf-app/dist/vue3-pdf-app.umd.js" is strongly discouraged as it poses security risks and may cause issues with minification."

Will you be fixing this?

Thanks
Roland

**Comment by stellR42** [comment]
The eval warning comes directly from pdf.js, so it shouldn't be a matter of concern.
I hope to be able to keep this package up to date but I can't guarantee it.
